server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:schema.sql
    data: classpath:data.sql
    url: jdbc:mysql://localhost:3306/springCloud?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:


logging:
  level:
    root: info
    org.hibrenate: info
    org.hibrenate.type.descriptor.sql.BasicBinder: trace
    org.hibrenate.type.descriptor.sql.BasicExractor: trace

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



