server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/


  instance:
    prefer-ip-address: true
spring:
  application:
    name: service-file-upload

  http:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2500MB


